Replace deprecated command with environment file
kairos-io/kairos pull request #1871
Opened 2023-10-01 11:31 UTC by jongwooo

**What this PR does / why we need it**:

Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

I found the workflow files that use `set-output` command through the following command:

```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```

**AS-IS**

```yaml
echo "::set-output name=matrix::{\"include\": $content }"
```

**TO-BE**

```yaml
echo "matrix={\"include\": $content }" >> $GITHUB_OUTPUT
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1870

2023-10-02 07:18 UTC, mauromorales requested changes
Hi @jongwooo thanks for opening the PR! I see that the output is now moved into the ENV var, but I think you might still need to change the consumers e.g., https://github.com/kairos-io/kairos/blob/master/.github/workflows/image.yaml#L65 to also read from that ENV var.

2023-10-05 14:13 UTC, mauromorales commented
While this does seem to put the content in the output, it seems to have some characters that break it see https://github.com/kairos-io/kairos/actions/runs/6420178340

> Error when evaluating 'strategy' for job 'framework'. .github/workflows/image-pr.yaml (Line: 41, Col: 15): Error parsing fromJson,.github/workflows/image-pr.yaml (Line: 41, Col: 15): Unexpected character encountered while parsing value: %. Path 'include', line 1, position 13.,.github/workflows/image-pr.yaml (Line: 41, Col: 15): Unexpected value ''

2023-10-11 15:59 UTC, jongwooo commented
> Error when evaluating 'strategy' for job 'framework'. .github/workflows/image-pr.yaml (Line: 41, Col: 15): Error parsing fromJson,.github/workflows/image-pr.yaml (Line: 41, Col: 15): Unexpected character encountered while parsing value: %. Path 'include', line 1, position 13.,.github/workflows/image-pr.yaml (Line: 41, Col: 15): Unexpected value ''

@mauromorales Sorry for the late reply. I'll take a look at what might be causing this.

2023-10-12 07:53 UTC, mauromorales commented
@jongwooo no worries and thanks! If it helps, I was testing it out with the following workflow https://github.com/kairos-io/kairos/pull/1889/files#diff-f8c07cbe8adb8afd573be281e6de56b7c0b2c1b88ee9624ab2f79ddacd1ca4b8L25-R41 and as a result you should see a bunch of flavors generate jobs

2024-01-04 15:41 UTC, closed without merging

2024-01-04 15:41 UTC, mauromorales commented
No progress here and some conflicts so I will close but feel free to re-open any time.