:penguin: sorted packages in dockerfiles and removed some duplicates
kairos-io/kairos pull request #787
Opened 2023-01-30 21:33 UTC by c0ffee

Signed-off-by: Martin Schuessler <1407812+c0ffee@users.noreply.github.com>

**What this PR does / why we need it**:
Sorted packages in existing dockerfiles

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #786

2023-01-30 21:37 UTC, mauromorales requested changes
Thanks for this one, I agree it's so much better to consume when sorted. I'd say let's take the opportunity to remove any duplicated packages

2023-01-30 21:37 UTC, mauromorales commented on images/Dockerfile.alpine-arm-rpi
> +      coreutils \
looks like we had duplications already

2023-01-30 21:37 UTC, mauromorales commented on images/Dockerfile.alpine-arm-rpi
> +      curl \
this one too

2023-01-30 21:37 UTC, mauromorales commented on images/Dockerfile.alpine-arm-rpi
> +      e2fsprogs \
so do these ... will not overflow with more comments but I guess is the same in other files

2023-01-30 21:45 UTC, c0ffee commented
good point i hope i got them now all

2023-01-30 22:36 UTC, mauromorales approved these changes
LGTM

2023-01-31 07:44 UTC, Itxaka approved these changes

2023-01-31 08:35 UTC, mudler commented
Fails on https://github.com/kairos-io/kairos/issues/781 which is unrelated, merging! Thanks @c0ffee !

2023-01-31 08:35 UTC, merged